apiVersion: v1 
kind: Service 
metadata:
  labels:
    app.kubernetes.io/name: group2-ch-eks-cluster 
    app.kubernetes.io/instance: group2-ch-eks-cluster-instance
    app.kubernetes.io/version: "1.0.0" 
    app.kubernetes.io/component: backend 
    app.kubernetes.io/managed-by: kubectl
  name: group2-default-eks-service 
spec:
  selector:
    app: todoeks
  type: NodePort
  ports:
    - protocol: TCP 
      port: 80
      targetPort: 3000